Update terraform destroy in actions

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -109,11 +109,13 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run:
-          set -e
-          terraform apply -auto-approve tfplan || \
-          (echo "Terraform apply failed, destroying resources..." && terraform destroy -auto-approve)
-        working-directory: terraform
+        run: |
+          terraform apply -auto-approve tfplan || {
+          echo "Terraform apply failed, destroying resources..."
+          terraform destroy -auto-approve
+          exit 1
+          }
+          working-directory: terraform
 
       - name: Output Terraform state info
         run: |
